import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { PENDING } from './pending';

/**
 * THE PLACEHOLDER GUARD.
 *
 * `pending.ts` holds the drafts of every sentence the venue rewrite cannot publish yet, each with
 * its `[CLAY: ...]` gap marked. That is a useful thing to have and a dangerous thing to have, for
 * one reason: a draft is finished prose with a hole in it, so it reads like copy, and copy gets
 * pasted. The failure mode is not subtle and it is not hypothetical for this repo — a figure
 * inherited from a constant went live for a few hours on 2026-07-28 at £150,000, below cost, and
 * the test binding the page to that constant was green throughout.
 *
 * So the invariant is stated as an ABSENCE and swept over everything, rather than asserted file by
 * file: the marker may appear in the registry and nowhere else in the repo's source or in anything
 * it publishes. A new page, a new copy module, a hand-edited mirror — all of them are covered the
 * day they are added, because the sweep does not know or care what files exist.
 *
 * Sweeping the PUBLIC directory as well is the half that catches the realistic mistake. The agent
 * mirrors and llms.txt are generated by `GEN=1`, and a `GEN=1` run is exactly the moment a
 * placeholder that had crept into a component would be baked into a committed file and served at
 * `/agent/questions.md` to every non-JavaScript reader of the site.
 */
const SRC = fileURLToPath(new URL('.', import.meta.url));
const PUBLIC = fileURLToPath(new URL('../public/', import.meta.url));

/** The registry is the one file allowed to carry a marker; it is what a marker is FOR. */
const REGISTRY = 'pending.ts';

/** Every readable text file under a root, recursively. Binary and vendor trees are skipped. */
function textFiles(root: string): string[] {
  const skip = new Set(['node_modules', 'vendor', 'assets', '.git', 'dist']);
  const ext = /\.(ts|tsx|js|jsx|mjs|md|txt|xml|json|html|css)$/;
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir)) {
      if (skip.has(name)) continue;
      const full = dir + name;
      if (statSync(full).isDirectory()) walk(full + '/');
      else if (ext.test(name)) out.push(full);
    }
  };
  walk(root);
  return out;
}

/**
 * The marker, matched as a string rather than a regex with a character class, because the point is
 * to catch the literal token the spec writes and the drafts carry.
 *
 * Split across a concatenation so that THIS FILE does not itself contain the marker it bans, which
 * would make the sweep fail on its own guard. The joined value is the real token.
 */
const MARKER = '[CLAY' + ':';

describe('no unfilled placeholder reaches a reader', () => {
  it('sweeps a non-empty set of files (a sweep over nothing passes trivially)', () => {
    // The repo's own law, learned from a for-loop over zero matches that guarded nothing while
    // staying green: every sweep asserts it actually swept something.
    expect(textFiles(SRC).length).toBeGreaterThan(50);
    expect(textFiles(PUBLIC).length).toBeGreaterThan(3);
  });

  it('the [CLAY] marker appears in the registry and nowhere else in src/', () => {
    const offenders = textFiles(SRC)
      .filter((f) => !f.endsWith(REGISTRY) && !f.endsWith('pending.test.ts'))
      .filter((f) => readFileSync(f, 'utf8').includes(MARKER))
      .map((f) => f.slice(SRC.length));
    expect(
      offenders,
      `a drafted placeholder has been pasted into live copy: ${offenders.join(', ')}`,
    ).toEqual([]);
  });

  it('nothing the site publishes carries a marker', () => {
    // public/ is what a browser, a crawler and an agent actually fetch: the mirrors, llms.txt,
    // the sitemap, robots.txt.
    const offenders = textFiles(PUBLIC)
      .filter((f) => readFileSync(f, 'utf8').includes(MARKER))
      .map((f) => f.slice(PUBLIC.length));
    expect(offenders, `published files carry a placeholder: ${offenders.join(', ')}`).toEqual([]);
  });

  /**
   * A `value` draft is a fill-in-the-blank and must SHOW its blank. A finished-looking sentence
   * with the hole already closed over is one paste away from publishing a guess, which is the
   * failure this whole registry exists to prevent.
   *
   * A `confirmation` draft is complete by nature and must NOT be required to carry a marker: what
   * is missing there is not a word, it is the evidence. This distinction was not in the first
   * draft of the registry — the test found it, by failing on the level-access entry, whose copy
   * ("Level throughout, no threshold, no step.") is a finished sentence that may simply be false.
   * That is the more dangerous kind of pending, because it reads as done.
   */
  it('a fill-in-the-blank draft shows its blank', () => {
    const values = PENDING.filter((p) => p.awaiting === 'value' && p.draft);
    expect(values.length, 'no value drafts to check').toBeGreaterThan(0);
    for (const p of values) {
      expect(p.draft, `${p.id}: a value draft with no visible gap`).toContain(MARKER);
    }
  });

  it('a draft awaiting confirmation is complete prose, not a blank', () => {
    for (const p of PENDING) {
      if (p.awaiting === 'confirmation' && p.draft) {
        expect(p.draft, `${p.id}: this is a blank, so it should be awaiting: 'value'`).not.toContain(
          MARKER,
        );
      }
    }
  });
});

describe('the pending registry stays readable', () => {
  it('ids are unique, so a PENDING(id) comment can only point at one thing', () => {
    const ids = PENDING.map((p) => p.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const id of ids) expect(id).toMatch(/^[a-z0-9-]+$/);
  });

  it('every entry says what is needed and what it is costing', () => {
    for (const p of PENDING) {
      // `blocks` is the field that stops this being a TODO list. A debt with no stated cost is a
      // debt nobody prioritises, and the whole point of the file is that these are ranked by what
      // they cost today rather than by spec item number.
      expect(p.needs.length, `${p.id}: needs is too short to act on`).toBeGreaterThan(30);
      expect(p.blocks.length, `${p.id}: blocks does not say what it is costing`).toBeGreaterThan(40);
      expect(p.item).toBeGreaterThan(0);
    }
  });

  it('is not empty, and when it is, this file and pending.ts are deleted together', () => {
    // A registry that has emptied out has done its job; leaving it behind is how a stale map ends
    // up at the top of the next agent's session. If this assert is what went red, delete both files.
    expect(PENDING.length).toBeGreaterThan(0);
  });
});
